name: EasySigns
main: nu.nerd.easysigns.EasySigns
description: Create signs with custom actions.
author: ["redwall_hp", "bermudalocket", "Nerd.nu"]
depend: [BlockStore]
api-version: 1.13
version: ${project.version}


permissions:
  easysigns.commands.*:
    description: EasySigns commands
    children:
      easysigns.commands.easy-sign: true
      easysigns.commands.easy-sign-delete: true
      easysigns.commands.easy-sign-info: true
      easysigns.commands.easy-sign-remove: true
      easysigns.commands.easy-sign-reorder: true
      easysigns.commands.easy-sign-copy: true
      easysigns.commands.easy-sign-paste: true
  easysigns.commands.easy-sign:
    description: Access to the /easy-sign command
  easysigns.commands.easy-sign-delete:
    description: Access to the /easy-sign-delete command
  easysigns.commands.easy-sign-info:
    description: Access to the /easy-sign-info command
  easysigns.commands.easy-sign-remove:
    description: Access to the /easy-sign-remove command
  easysigns.commands.easy-sign-reorder:
    description: Access to the /easy-sign-reorder command
  easysigns.commands.easy-sign-copy:
    description: Access to the /easy-sign-copy command
  easysigns.commands.easy-sign-paste:
    description: Access to the /easy-sign-paste command


commands:
  easy-sign:
    usage: /easy-sign <action> [parameters]
    description: Add an action to a sign
    permission: easysigns.commands.easy-sign
    permission-message: You don't have permission to do that.
  easy-sign-delete:
    usage: /easy-sign-delete
    description: Remove all actions and unregister an EasySign
    permission: easysigns.commands.easy-sign-delete
    permission-message: You don't have permission to do that.
  easy-sign-info:
    usage: /easy-sign-info
    description: Inspect an EasySign's actions
    permission: easysigns.commands.easy-sign-info
    permission-message: You don't have permission to do that.
  easy-sign-remove:
    usage: /easy-sign-remove <index>
    description: Remove an action from a sign.
    permission: easysigns.commands.easy-sign-remove
    permission-message: You don't have permission to do that.
  easy-sign-reorder:
    usage: /easy-sign-reorder <from> <to>
    description: Reorder sign actions
    permission: easysigns.commands.easy-sign-reorder
    permission-message: You don't have permission to do that.
  easy-sign-copy:
    usage: /easy-sign-copy
    description: Copy the sign's actions to the clipboard
    permission: easysigns.commands.easy-sign-copy
    permission-message: You don't have permission to do that.
  easy-sign-paste:
    usage: /easy-sign-paste
    description: Paste the copied sign actions to a new block.
    permission: easysigns.commands.easy-sign-paste
    permission-message: You don't have permission to do that.
